version: '2'

services:

  nginx01:
    #image: nginx
    build:
      context: ./
      dockerfile: proxy.docker
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  app001:
      build:
          context: ./
          dockerfile: node.docker
      volumes:
        - ./public:/usr/src/app
      ports:
          - "8081:3000"

  app002:
      build:
          context: ./
          dockerfile: node.docker
      volumes:
        - ./public:/usr/src/app
      ports:
          - "8082:3000"

  # app001:
  #   build:
  #     context: ./
  #     dockerfile: proxy.docker
  #   ports:
  #     - "8081:80"
  #
  # app002:
  #   build:
  #     context: ./
  #     dockerfile: proxy.docker
  #   ports:
  #     - "8082:80"

# DOES NOT WORK
  # app001:
  #   build:
  #     context: ./
  #     dockerfile: httpd.docker
  #   ports:
  #     - "8081:80"
  #
  # app002:
  #   build:
  #     context: ./
  #     dockerfile: httpd.docker
  #   ports:
  #     - "8082:80"

